core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('education/', views.education, name='education')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/urls.py
#portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('projects/', include(('projects.urls', 'projects'), namespace='projects'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.project_list, name='list'),
    path('<slug:slug>/', views.project_detail, name='detail'),
]

projects/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

class TechnologyType(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Technology Type")

    def __str__(self):
        return self.name
    
class ProjectType(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Project Type")

    def __str__(self):
        return self.name

class Technology(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name="Technology Name")
    type = models.ForeignKey(
        TechnologyType,
        on_delete=models.CASCADE,
        related_name="technologies",
        verbose_name="Type"
    )

    def __str__(self):
        return f"{self.name} ({self.type.name})"

class Project(models.Model):
    title = models.CharField(max_length=200, verbose_name="Project Title")
    slug = models.SlugField(max_length=250, unique=True, blank=True, verbose_name="URL Slug")
    link = models.URLField(
        help_text="Enter a link to the project or repository.",
        blank=True,
        null=True
    )
    description = models.TextField(verbose_name="Project Description")
    created = models.DateTimeField(default=timezone.now, verbose_name="Date Created", editable=True)
    updated = models.DateTimeField(auto_now=True, verbose_name="Last Updated")
    image = models.ImageField(
        upload_to='images/',
        blank=True,
        null=True,
        help_text="Upload an image for the project.",
        verbose_name="Project Image"
    )
    file = models.FileField(
        upload_to='files/',
        blank=True,
        null=True,
        help_text="Upload a file related to the project.",
        verbose_name="Project File"
    )
    technologies = models.ManyToManyField(Technology, related_name="projects", verbose_name="Technologies Used")
    projecttype = models.ManyToManyField(ProjectType, related_name="projects", verbose_name="Project Types")
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def technology_list(self):
        """Returns a comma-separated list of technologies used in this project."""
        return ", ".join(tech.name for tech in self.technologies.all())
    
    def type_list(self):
        """Returns a comma-separated list of all project categories project falls under."""
        return ", ".join(type.name for type in self.projecttype.all())

    class Meta:
        ordering = ["-created"]
        verbose_name = "Project"
        verbose_name_plural = "Projects"

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Count
from .models import Project, Technology, ProjectType

def project_list(request):
    technologies = Technology.objects.filter(projects__isnull=False) \
                                      .annotate(project_count=Count('projects')) \
                                      .order_by('name')
    
    project_types = ProjectType.objects.filter(projects__isnull=False) \
                                       .annotate(project_count=Count('projects')) \
                                       .order_by('name')
    
    selected_techs = request.GET.getlist('technologies')
    selected_types = request.GET.getlist('projecttype')
    
    projects = Project.objects.all()
    if selected_techs:
        projects = projects.filter(technologies__name__in=selected_techs).distinct()
    if selected_types:
        projects = projects.filter(projecttype__name__in=selected_types).distinct()
    
    context = {
        'projects': projects,
        'technologies': technologies,
        'projecttype': project_types,
        'selected_techs': selected_techs,
        'selected_types': selected_types
    }
    return render(request, 'projects/list.html', context)

def project_detail(request, slug):
    project = get_object_or_404(Project, slug=slug)
    return render(request, 'projects/detail.html', {'project': project})

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'projects/project_styles.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'shared/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'shared/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'shared/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'shared/favicon_io/site.webmanifest' %}">

</head>
<body>
    <nav>
        <div class="nav-container">
            <h1 class="logo"><a href="{% url 'home' %}">Matthew Dwyer</a></h1>
            <div class="hamburger" onclick="toggleNav()">
                <span></span>
                <span></span>
                <span></span>
            </div>
            <div class="nav-link" id="navLinks">
                <a href="{% url 'home' %}">Home</a>
                <a href="{% url 'projects:list' %}">Projects</a>
                <a href="{% url 'education' %}">Education</a>
                <a href="{% url 'contact' %}">Contact</a>
            </div>
        </div>
    </nav>
    <main>
            {% block content %}{% endblock %}
        </div>
    </main>

    <footer>
        <div class="container">
            <p>&copy; <span id="year"></span> Matthew Dwyer</p>
        </div>
    </footer>
    <script>
        document.getElementById("year").textContent = new Date().getFullYear();
        function toggleNav() {
            const navLinks = document.getElementById('navLinks');
            navLinks.classList.toggle('show');
        }
    </script>
</body>
</html>

projects/templates/projects/detail.html
{% extends 'projects/base.html' %}
{% block content %}
<title>{{ project.title }}</title>
<div class="project-detail">
    <a href="{% url 'projects:list' %}">Projects</a>
    <h2>{{ project.title }}</h2>
    {% if project.image %}
    <img src="{{ project.image.url }}" alt="{{ project.title }}">
    {% endif %}
</div>
<div class="project-description-main">
    <h3><strong>Created: {{ project.created }} </strong></h3>
    <h3><strong>Last Updated: {{ project.updated }}</strong></h3>
    <p>{{ project.description|linebreaksbr }}</p>
    <p><strong> - Technologies Used:</strong> {{ project.technology_list }}</p>
    <p><strong> - Project Type:</strong> {{ project.type_list }}</p>
    {% if project.file %}
        <a href="{{ project.file.url }}" target="_blank">Download File</a>
    {% endif %}
    {% if project.link %}
        <a href="{{ project.link }}" target="_blank">View Code</a>
    {% endif %}
</div>
{% endblock %}

projects/templates/projects/list.html
{% extends 'projects/base.html' %}
{% load static %}
{% block content %}
<title>Projects</title>
<div class="projects-container">
    <h2>My Projects</h2>
    <form method="get" action="{% url 'projects:list' %}">
        <label for="technologies">Filter:</label>
    
        <div class="dropdown-container">
            <button type="button" onclick="toggleDropdown('tech-dropdown')">Technologies</button>
            <div id="tech-dropdown" class="dropdown" style="display: none;">
                {% for tech in technologies %}
                    <label class="checkbox-option">
                        <input type="checkbox" name="technologies" value="{{ tech.name }}" 
                               {% if tech.name in selected_techs %}checked{% endif %}>
                        {{ tech.name }} ({{ tech.project_count }})
                    </label>
                {% endfor %}
            </div>
        </div>
    
        <div class="dropdown-container">
            <button type="button" onclick="toggleDropdown('type-dropdown')">Type</button>
            <div id="type-dropdown" class="dropdown" style="display: none;">
                {% for type in projecttype %}
                    <label class="checkbox-option">
                        <input type="checkbox" name="projecttype" value="{{ type.name }}" 
                               {% if type.name in selected_types %}checked{% endif %}>
                        {{ type.name }} ({{ type.project_count }})
                    </label>
                {% endfor %}
            </div>
        </div>
    
        <button type="submit">Filter</button>
        <button type="filter" onclick="resetSelection()">Reset</button>
    </form>
    

    <div class="projects-grid">
        {% for project in projects %}
            <a href="{% url 'projects:detail' project.slug %}" class="project-card">
                <h3>{{ project.title }} - {{ project.created }}</h3>
                {% if project.image %}
                    <img src="{{ project.image.url }}" alt="Project Image">
                {% endif %}
                <p>{{ project.description|truncatewords:70 }}</p>
                <p><strong>- Technologies Used:</strong> {{ project.technology_list }}</p>
                <p><strong>- Project Type:</strong> {{ project.type_list }}</p>
            </a>
        {% endfor %}
    </div>    
</div>
<script>
    function toggleDropdown(dropdownId) {
    const dropdown = document.getElementById(dropdownId);
    const isDisplayed = dropdown.style.display === 'block';

    document.querySelectorAll('.dropdown').forEach(d => d.style.display = 'none');

    dropdown.style.display = isDisplayed ? 'none' : 'block';
    }
    function resetSelection() {
    document.querySelectorAll("input[type='checkbox']").forEach(checkbox => checkbox.checked = false);
    }
</script>
{% endblock %}